//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VideosOnDemandEntityDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class director
    {
        public int id { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string gender { get; set; }
        public Nullable<int> fk_film_id { get; set; }
        public Nullable<int> fk_television_id { get; set; }
    
        public virtual film film { get; set; }
        public virtual television television { get; set; }
    }
}
