//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VideosOnDemandEntityDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class film
    {
        public film()
        {
            this.directors = new HashSet<director>();
            this.usernames = new HashSet<username>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> length_minute { get; set; }
        public Nullable<System.DateTime> release_date { get; set; }
        public Nullable<int> fk_genre_id { get; set; }
    
        public virtual ICollection<director> directors { get; set; }
        public virtual genre genre { get; set; }
        public virtual ICollection<username> usernames { get; set; }
    }
}
