//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VideosOnDemandEntityDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class genre
    {
        public genre()
        {
            this.actors = new HashSet<actor>();
            this.films = new HashSet<film>();
            this.televisions = new HashSet<television>();
            this.usernames = new HashSet<username>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<actor> actors { get; set; }
        public virtual ICollection<film> films { get; set; }
        public virtual ICollection<television> televisions { get; set; }
        public virtual ICollection<username> usernames { get; set; }
    }
}
